project:
  type: website

website:
  title: "Matheus Ferreira"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: media.qmd
        text: Media

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



