project:
  type: website

website:
  title: "Matheus Ferreira"
  open-graph: true
  twitter-card: true
  sidebar:
    tools:
      - icon: twitter
        href: https://twitter.com/matferreira19
      - icon: github
        href: https://github.com/mathpol
      - icon: linkedin
        href: https://www.linkedin.com/in/matheus-ferreira-20417916/
      - icon: mailbox
        href: mailto:ferreira.dcp@gmail.com
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Apresentação
      - href: research.qmd
        text: Publicações
      - href: experiencia.qmd
        text: Experiência
      - href: education.qmd
        text: Formação
      - text: CV
        href: https://drive.google.com/file/d/1-SNhRy6TVPA5ipUJVhv6483ioPgGiaOE/view?usp=sharing
      - href: media.qmd
        text: Mídias
      - href: award.qmd
        text: Prêmios
      - href: parecerista.qmd
        text: Bancas e Pareceres

format:
  html:
    theme: cosmo
    linkcolor: "#2171b5"
    css: styles.css
    toc: true

