---
title: "Experiência Profissional"
---

::: panel-tabset

# **Vínculos ativos**


## **Núcleo Interdisciplinar em Políticas Públicas (NIPP - UFSC)**
(06/2023 - atual)

Desenvolvo pesquisa de Opinião Pública sobre Clivagens Políticas na América Latina, compreendendo seus determinantes e efeitos para a democracia e o comportamento político dos eleitores. Trabalha como *survey expert*, analista de dados e acompanhamento de alunos de graduação e pós-graduação.


## **Centro de Estudos do Comportamento Político (CECOMP - UFMG)**
(03/2018 - atual)

Atuo no campo de pesquisa sobre Opinião Pública e os diversos tipos de comportamento político, especialmente o eleitoral. Minha tese de doutorado explorou a relação entre religião evangélica e voto nas eleições de 2018 no Brasil. Baixe a tese clicando [aqui](https://drive.google.com/file/d/1bReOqINuA9MNKWw3DTVTIul-TG_SGWhH/view?usp=sharing)

[Twitter](https://twitter.com/cecomp_br) | [Facebook](https://www.facebook.com/CeComPolitico)



# **Vínculos encerrados**


## **Incentiv**
(10/2022 - 04/2023)

Responsável por desenvolver indicadores de desempenho e monitorá-los, com o objetivo de orientar as empresas a montarem seus portfólios. Realizei extração e manipulação de dados e auxiliei o desenvolvimentos de dashboards em Power BI. [Incentiv.me](https://site.incentiv.me/)


## **IPESPE – Instituto de Pesquisas Sociais, Políticas e Econômicas** 
(2022 e 2024)

Em 2022, fui resposnável por elaborar um modelo de agregação de dados eleitorais usando técnicas de Machine Learning e projetando cenários com modelos de séries temporais.

Em 2024, coordenei uma equipe de dados, para implementação e atualização do modelo construído em 2022.

## **Instituto Federal do Rio Grande do Sul**
(07/2022 - 12/2022)

Professor de Sociologia em 15 turmas dos Cursos Técnicos Integrados.

## **Fundação João Pinheiro** 
(10/2021 - 07/2022)

Avaliei a efetividade de políticas públicas do Estado de Minas Gerais, especialmente aquelas com impacto na Educação. Recentemente trabalhei com análise de efetividade do programa Minas Comunica II, utilizando dados secundários de diversas fontes (dados do INEP e do Índice Mineiro de Responsabilidade Social). Também contribuí para o programa de Transformação Digital, que desenvolve rotinas de programação para gestão de dados da Fundação.

## **Universidade Federal de Juiz de Fora (UFJF)**
(07/2018 - 12/2018)

Professor de três disciplinas: "Introdução à Ciência Política", "Políticas Públicas e Sociedade" e "Estudos Culturais".

## **Colégio dos Santos Anjos**
(03/2013 - 12/2017)

Professor de Sociologia para turmas do Ensino Médio da Educação Básica.

## **Colégio Equipe**
(02/2016 - 12/2017)

Professor de Sociologia e Filosofia para turmas do Ensino Médio e Fundamental da Educação Básica.

:::