---
title: "Mídias"
---


::: panel-tabset

### **Jornais**

* FERREIRA, M. G. M.. Voto evangélico ou voto dos evangélicos? O papel da religião na decisão do voto. Congresso em Foco, 25 set. 2022.

* FERREIRA, M. G. M.. Questões que podem definir as eleições 2022: veja em seis pontos o que vai mover a opinião pública. O Globo, 14 ago. 2022.


### **Entrevistas**

* FERREIRA, M. G. M.. Das evangelikale Denkmal Bolsonaro bröckelt: Wahlkampf- Endspurt in Brasilien. 2022. (Programa de rádio ou TV/Comentário). 

* FERREIRA, M. G. M.. Agenda do Poder: CNBB lamenta 'exploração da fé e da religião' no 2º turno das eleições. 2022. (Programa de rádio ou TV/Entrevista). 

* FERREIRA, M. G. M.. No Brasil, para captar o voto religioso, o diabo não está só nos detalhes. 2022. (Programa de rádio ou TV/Comentário). 

* FERREIRA, M. G. M.. Especialista opina que afastamento de Cunha não influencia impeachment de Dilma. 2016. (Programa de rádio ou TV/Entrevista). 

* FERREIRA, M. G. M.. Cientista político analisa possíveis resultados para segundo turno em Juiz de Fora. 2016. (Programa de rádio ou TV/Entrevista). 

* FERREIRA, M. G. M.. Jovens adiam início da participação em processos eleitorais. 2016. (Programa de rádio ou TV/Entrevista).

:::