---
title: "Trabalhos Publicados"
---

## **Artigos**

::: panel-tabset


### **Publicados**

* **(2021)** FERREIRA, MATHEUS GOMES MENDONÇA; FUKS, MARIO . O hábito de frequentar cultos como mecanismo de mobilização eleitoral: o voto evangélico em Bolsonaro em 2018. REVISTA BRASILEIRA DE CIÊNCIA POLÍTICA, v. X, p. 1, 2021. [Link](https://www.scielo.br/j/rbcpol/a/fWvcZ49qvhjrpB9dNBK6sxB/?lang=pt)

* **(2021)** FERREIRA, M. G. M.; PACCELI, G. . E depois do fim? Transições políticas na crise da democracia contemporânea. CONTEMPORÂNEA (ONLINE), v. 11, p. 702-716, 2021. [Link](https://www.contemporanea.ufscar.br/index.php/contemporanea/article/view/848)

* **(2020)** FERREIRA, M. G. M.. Os fundamentos religiosos do Capitalismo e da Democracia e uma preocupação com a liberdade: um diálogo entre Tocqueville e Weber. NUMEN: REVISTA DE ESTUDOS E PESQUISA DA RELIGIÃO, v. 23, p. 129-137, 2020. [Link](https://periodicos.ufjf.br/index.php/numen/article/view/29959)

* **(2019)** FERREIRA, M. G. M.. Dilemas Sulinos: desafios para a integração do Mercosul. PRELÚDIOS: REVISTA DO PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS SOCIAIS DA UFBA, v. 8, p. 77, 2019.

* **(2019)** PACCELI, G. ; FERREIRA, MATHEUS GOMES MENDONÇA . Apresentação. CSONLINE (UFJF), v. 1, p. 06-08, 2019.
Citações:1

* **(2016)** FERREIRA, M. G. M.; TAVARES JR., F. . DE 2013 A 2016: AS RUAS E RESSIGNIFICAÇÕES POLÍTICAS. CSONLINE - REVISTA ELETRÔNICA DE CIÊNCIAS SOCIAIS, v. 1, p. 43, 2016.

* **(2011)** RIOS, C.; PEDROSA, D.; FERREIRA, M. G. M.; MACIEL, R.; RODRIGUES, T. M.; ASSIS, W. PARLAMENTO JOVEM 2010: EDUCAÇÃO POLÍTICA EM PERSPECTIVA. CSONLINE (UFJF), v. 1, p. 153-168, 2011.




### **Submetidos**

* **[Under Review]** Religião, Sexo e Cor/Raça: nuances do efeito da identidade evangélica sobre o voto em Bolsonaro em 2018.

* **[Under Review]** Cross and Sword: Religious Backlash and Populism in Brazil’s 2018 Electoral Crusadeord:Religious Backlash and Populism in Brazil’s 2018 Electoral Crusade.


:::


## **Capítulos de livros**

::: panel-tabset


### **Publicados**


* **(2023)** VENTURELLI, Gustavo; TAMAKI, Eduardo Ryô; FERREIRA, Matheus Gomes Mendonça. The Sharp-Tongued Loudmouth: Incivility and Debasement in Brazil's President Jair Bolsonaro's YouTube Livestreams. In: Debasing Political Rhetoric: Dissing Opponents, Journalists, and Minorities in Populist Leadership Communication. Singapore: Springer Nature Singapore, 2023. p. 73-86. [Link](https://link.springer.com/chapter/10.1007/978-981-99-0894-3_5)

* **(2021)** 8.	(2021) TAMAKI, E. R.; MENDONÇA, R. F.; FERREIRA, M. G. M.. The Symbolic Construction of a Messiah: Jair Bolsonaro’s Public, Christian Discourse. In: When Politicians Talk. Springer, Singapore, 2021. p. 73-89. [Link](https://link.springer.com/chapter/10.1007/978-981-16-3579-3_5)


### **Submetidos**

FERREIRA, M. G. M.; FUKS, M.; SMITH, A. E. A Conversion to the Right: The Case of the 2018 Election of Jair Bolsonaro in Brazil.

:::